version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: newPassword
    volumes:
      - ./database/db.sql:/docker-entrypoint-initdb.d/db.sql
    networks:
      - default

  golang:
    image: golang
    restart: always
    build: "./"
    ports:
      - 80:80
    networks:
      - default


networks:
  default:
